version: '3'

tasks:
  version:
    cmds:
      - |
        myVar="1.0.0-{{.BRANCH_NAME}}+{{.RUN_NUMBER}}"
        if [[ {{.BRANCH_NAME}} == "releases/"*" ]]; then
          EBSI_ENV="prod"
        elif [[ {{.BRANCH_NAME}} == 'master' ]]; then
          EBSI_ENV="prod"
        elif [[ {{.BRANCH_NAME}} == 'staging' ]]; then
          EBSI_ENV="staging"
        elif [[ {{.BRANCH_NAME}} == 'develop' ]]; then
          EBSI_ENV="ci"
        elif [[ {{.BRANCH_NAME}} == 'qa' ]]; then
          EBSI_ENV="qa"
        else
          EBSI_ENV="ci"
        fi
        echo "VERSION=$myVar" >> $GITHUB_OUTPUT
        echo "EBSI_ENV=$EBSI_ENV" >> $GITHUB_OUTPUT
    
