version: '3'

vars:
  CI: '{{.CI | default false}}'
  EBSI_ENV:
    sh: |
      if [[ {{.BRANCH_NAME}} == "releases/"* ]]; then
        EBSI_ENV="prod"
      elif [[ {{.BRANCH_NAME}} == 'main' || {{.BRANCH_NAME}} == 'master' ]]; then
        EBSI_ENV="prod"
      elif [[ {{.BRANCH_NAME}} == 'staging' ]]; then
        EBSI_ENV="staging"
      elif [[ {{.BRANCH_NAME}} == 'develop' ]]; then
        EBSI_ENV="ci"
      elif [[ {{.BRANCH_NAME}} == 'qa' ]]; then
        EBSI_ENV="qa"
      else
        EBSI_ENV="ci"
      fi
      echo $EBSI_ENV
    
tasks:
  version:
    desc: Get Ebsi Environment name and Version
    cmds:
      - task: get_env
      - task: version2

  get_env:
    cmds:
      - |
        echo $EBSI_ENV
        echo "EBSI_ENV=$EBSI_ENV" >> $GITHUB_OUTPUT

  version2:
    cmds:
      - |
        myVer={{.NEW_VERSION}}
        echo $CI
        echo $myVer
        if [$CI = false]; then
        exit 0
        fi
        echo "NEW_VERSION=$myVer" >> $GITHUB_OUTPUT
        echo "NEW_TAG=v$myVer" >> $GITHUB_OUTPUT
    vars:
      NEW_VERSION:
        sh: echo "1.0.0-{{.BRANCH_NAME}}+{{.RUN_NUMBER}}"

  archive:
    desc: Create a GitHub release
    cmds:
      - gh release create --generate-notes --target {{.BRANCH_NAME}} "v{{.VERSION}}" {{.ARTIFACTS}}
