name: CI

on:
    push:
        branches:
            - main
            - master
            - develop
env:
    GH_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

jobs:
    first:
        uses: ./.github/workflows/first.yml
        secrets: inherit

    second:
        uses: ./.github/workflows/second.yml
        secrets: inherit
        
    release:
        runs-on: ubuntu-latest
        if: startsWith(github.ref_name, 'master')
        needs: [first, second]
        steps:
          - name: install nix
            uses: DeterminateSystems/nix-installer-action@v4
            with:
              github-token: $GH_TOKEN
              diagnostic-endpoint: ''
              extra-conf: |
                access-tokens = github.com="$GH_TOKEN"

          - name: setup nix cache
            uses: DeterminateSystems/magic-nix-cache-action@v2
            with:
              diagnostic-endpoint: ''
                        
          - name: Download Artifacts
            id: download-artifacts
            uses: actions/download-artifact@v3
            with:
                path: ./dist/artifacts
    
          - name: release
            run: |
                nix develop -c task archive \
                BRANCH_NAME=$BRANCH_NAME \
                VERSION=${{ needs.first.outputs.VERSION }} \
                ARTIFACTS=./dist/artifacts/*