name: CI

on:
    push:
        branches:
            - main
            - master
env:
    GH_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    BRANCH_NAME: '${{ github.ref_name }}'
    RUN_NUMBER: '${{ github.run_number }}'  

jobs:
    version:
        runs-on: ubuntu-latest
        outputs:
            NEW_VERSION: ${{steps.version.outputs.VERSION}}
        steps:
            - name: Version
              id: version
              run: echo "VERSION=1.0.$RUN_NUMBER-$BRANCH_NAME+$RUN_NUMBER$RUN_NUMBER" >> $GITHUB_OUTPUT

            - name: debug
              run: echo $CI

    first:
        uses: ./.github/workflows/first.yml
        with:
          build_envs: [ct,prod]
        secrets: inherit
        
    second:
        uses: ./.github/workflows/second.yml
        secrets: inherit
        
    release:
        runs-on: ubuntu-latest
        if: startsWith(github.ref_name, 'master')
        needs: [version, first, second]
        steps:
          - uses: actions/checkout@v3

          - name: install nix
            uses: DeterminateSystems/nix-installer-action@v4
            with:
              github-token: $GH_TOKEN
              diagnostic-endpoint: ''
              extra-conf: |
                access-tokens = github.com="$GH_TOKEN"

          - name: setup nix cache
            uses: DeterminateSystems/magic-nix-cache-action@v2
            with:
              diagnostic-endpoint: ''
                        
          - name: Download Artifacts
            id: download-artifacts
            uses: actions/download-artifact@v3
            with:
                path: ./dist
    
          - name: release
            run: |
                nix develop -c task archive \
                BRANCH_NAME=$BRANCH_NAME \
                VERSION=${{ needs.version.outputs.NEW_VERSION }} \
                ARTIFACTS=./dist/artifacts/*
